### ISSUE TITLE
TT 3 Questao 2 Hash para String usando yaml

### ISSUE THREAD

**Issue by vanderleipinto** [vanderleipinto/TT3#4]
# Questão 2

O objetivo desta questão é extender a [solução acima](https://github.com/vanderleipinto/TT3/issues/1) de modo que o formato do string retornado seja configurável.
Considere um arquivo yaml no seguinte modelo. As chaves de primeiro nível (name, cpf, etc) representam atributos do hash e não são fixas (quer dizer, elas podem diferir de um arquivo yaml para outro). As chaves de segundo nível são sempre as mesmas: length, align, e padding.

**length**
Com quantos caracteres deve ser formatado esse campo no output. Se o conteúdo do campo ultrapassar esse comprimento, ele deve ser truncado.
__align__
Indica se o conteúdo do campo deve ser alinhado a esquerda ou a direita.
**padding**
Caso o conteúdo do cammpo seja mais curto que a length especificada, o padding indica se o espaço restante deve ser preenchido
com espaços em branco ou zero.

### Exemplo yaml 1
```yaml
# format-1.yaml
cpf:
  length: 11
  align: left
  padding: spaces
name:
  length: 14
  align: left
  padding: spaces
value:
  length: 8
  align: right
  padding: zeroes

``` 
Utilizando esse arquivo com o exemplo da questão anterior, o retorno esperado seria:

`"97905796671Maria Neusa de00001234\n44010762900Ricardo Fontes00000567"`

### Exemplo yaml 2

```yaml
# format-2.yaml
cpf:
  length: 14
  align: right
  padding: zeroes
value:
  length: 8
  align: right
  padding: zeroes
state:
  length: 14
  align: left
  padding: spaces
``` 
Utilizando esse arquivo com o exemplo da questão anterior, o retorno esperado seria:
`"0009790579667100001234Sao Paulo \n0004401076290000000567Rio Grande do "`

Nesta solução, além de receber a lista de hashes como argumento, o método solucao deve ler estas configurações de um arquivo yaml de
nome “format.yaml”.
Se preferir, fique a vontade para usar uma class ou module ao invés de só um método.
